services: 
  - name: docker:dind

variables: 
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build:staging:
  stage: build
  script:
    - echo "build"

deploy:staging:
  stage: deploy
  script:
    - echo "deploy"
  needs: ["build:staging"]